name: Build and Deploy
on: # 监听 main 分支上的 push 事件
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 构建环境使用 ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1  
        with:
          persist-credentials: false

      - name: Deploy # 将打包内容发布到 github page
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:  # 自定义环境变量
          branch: test
          folder: dist
          repository-name: pig-zhu/threeD/src # 这是我的 github page 仓库
          target-folder: /
          token: ${{ secrets.TOKEN }}
